/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Variant({
  'AI' : IDL.Null,
  'Computer' : IDL.Null,
  'Maths' : IDL.Null,
  'Commerce' : IDL.Null,
});
export const ScheduleEntry = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'subject' : Subject,
  'endTime' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addScheduleEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [ScheduleEntry],
      [],
    ),
  'deleteScheduleEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllScheduleEntries' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
  'getEntriesBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScheduleEntry)],
      ['query'],
    ),
  'updateScheduleEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Variant({
    'AI' : IDL.Null,
    'Computer' : IDL.Null,
    'Maths' : IDL.Null,
    'Commerce' : IDL.Null,
  });
  const ScheduleEntry = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'subject' : Subject,
    'endTime' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addScheduleEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [ScheduleEntry],
        [],
      ),
    'deleteScheduleEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllScheduleEntries' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
    'getEntriesBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScheduleEntry)],
        ['query'],
      ),
    'updateScheduleEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };