/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ScheduleEntry {
  'id' : bigint,
  'startTime' : string,
  'subject' : Subject,
  'endTime' : string,
  'note' : [] | [string],
}
export type Subject = { 'AI' : null } |
  { 'Computer' : null } |
  { 'Maths' : null } |
  { 'Commerce' : null };
export interface _SERVICE {
  'addScheduleEntry' : ActorMethod<
    [string, string, string, [] | [string]],
    ScheduleEntry
  >,
  'deleteScheduleEntry' : ActorMethod<[bigint], undefined>,
  'getAllScheduleEntries' : ActorMethod<[], Array<ScheduleEntry>>,
  'getEntriesBySubject' : ActorMethod<[string], Array<ScheduleEntry>>,
  'updateScheduleEntry' : ActorMethod<
    [bigint, string, string, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];